import re
import os
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass

from app.template_parser import ParsedTemplate, TemplateSection
from app.config import ABSTENTION_MSG


@dataclass
class CompiledSection:
    """Sezione compilata dal generatore."""
    section: TemplateSection
    generated_content: str
    is_abstention: bool = False         # True se il CRAG non ha trovato dati
    sources: list[str] = None           # file sorgente usati

    def __post_init__(self):
        if self.sources is None:
            self.sources = []


@dataclass
class CompiledDocument:
    """Documento finale assemblato."""
    template: ParsedTemplate
    sections: list[CompiledSection]
    generation_date: str = ""
    project_name: str = "MONAI Deploy App SDK"

    def __post_init__(self):
        if not self.generation_date:
            self.generation_date = datetime.now().strftime("%Y-%m-%d %H:%M")


def sanitize_content(text: str) -> str:
    """
    Rimuove residui di istruzioni del template dall'output dell'LLM.
    """
    # 1. Rimuove commenti HTML (<!-- ... -->) anche multi-riga
    text = re.sub(r"<!--.*?-->", "", text, flags = re.DOTALL)

    # 2. Rimuove placeholder angolari (<nome azienda>, <inserire qui>, ...)
    #    ma NON tag HTML legittimi come <br> o link markdown
    text = re.sub(r"<(?!br|http|a |/a|img)[A-Za-z][^>]*>", "", text)

    # 3. Rimuove placeholder tra parentesi quadre ...
    text = re.sub(r"\[(?:inserire|insert|TODO|enter|specify|add|fill)[^\]]*\]",
                  "", text, flags=re.IGNORECASE)

    # 4. Rimuove righe che sono pura istruzione (iniziano con keyword tipiche)
    cleaned_lines = []
    instruction_markers = [
        "describe here", "list here", "enter here", "specify here",
        "fill in", "add here", "update this", "note:", "todo:",
    ]
    for line in text.split("\n"):
        stripped = line.strip().lower()
        if any(stripped.startswith(marker) for marker in instruction_markers):
            continue
        cleaned_lines.append(line)
    text = "\n".join(cleaned_lines)

    # 5. Rimuove righe vuote multiple consecutive (pulizia finale)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def recompose_document(compiled: CompiledDocument) -> str:
    """
    Assembla un documento Markdown finale dalle sezioni compilate.
    """
    # --- HEADER ---
    lines = [f"# Compliance Report - {compiled.template.title}", "", f"**Repository:** {compiled.project_name}",
             f"**Template:** OpenRegulatory - {compiled.template.file_name}",
             f"**Generated by:** CRAG Compliance Analyzer", f"**Date:** {compiled.generation_date}", "",
             f"Questo report è stato generato automaticamente a partire dal template  "
             f"regolatorio OpenRegulatory: {compiled.template.title}.", ""]

    # --- RIEPILOGO COMPLETEZZA ---
    total = len(compiled.sections)
    filled = sum(1 for s in compiled.sections if not s.is_abstention)
    abstained = total - filled

    lines.append("---")
    lines.append("")
    lines.append(f"**Sezioni compilate:** {filled}/{total}")
    if abstained > 0:
        lines.append(f"**Sezioni con dati mancanti:** {abstained}")
        abstention_titles = [s.section.title for s in compiled.sections if s.is_abstention]
        lines.append(f"  - " + "\n  - ".join(abstention_titles))
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- SEZIONI ---
    for compiled_section in compiled.sections:
        section = compiled_section.section
        heading = "#" * section.level
        lines.append(f"{heading} {section.title}")
        lines.append("")

        if compiled_section.is_abstention:
            lines.append(f"> **[INFORMAZIONE NON DISPONIBILE]** {ABSTENTION_MSG}")
            lines.append("")
        else:
            # Pulisce residui di istruzioni template
            clean_content = sanitize_content(compiled_section.generated_content)
            lines.append(clean_content)
            lines.append("")

        # Fonti
        if compiled_section.sources:
            lines.append(f"*Fonti: {', '.join(compiled_section.sources)}*")
            lines.append("")

    return "\n".join(lines)


def save_document(content: str, output_path: str) -> None:
    """Salva il documento Markdown."""
    Path(output_path).parent.mkdir(parents = True, exist_ok = True)
    Path(output_path).write_text(content, encoding = "utf-8")
    print(f"  Documento salvato: {os.path.relpath(output_path)}")


def get_output_path(template: ParsedTemplate, output_dir: str) -> str:
    """Genera il percorso di output per il documento compilato."""
    stem = Path(template.file_name).stem
    date_str = datetime.now().strftime("%Y%m%d")
    filename = f"{stem}_compiled_{date_str}.md"
    return str(Path(output_dir) / filename)
