import re
import os
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass

from app.template_parser import ParsedTemplate, TemplateSection
from app.config import ABSTENTION_MSG


@dataclass
class CompiledSection:
    """Sezione compilata dal generatore."""
    section: TemplateSection
    generated_content: str
    is_abstention: bool = False         # True se il CRAG non ha trovato dati
    sources: list[str] = None           # file sorgente usati
    context: str = ""                   # testo grezzo dei chunk recuperati

    def __post_init__(self):
        if self.sources is None:
            self.sources = []


@dataclass
class CompiledDocument:
    """Documento finale assemblato."""
    template: ParsedTemplate
    sections: list[CompiledSection]
    generation_date: str = ""
    project_name: str = "MONAI Deploy App SDK"

    def __post_init__(self):
        if not self.generation_date:
            self.generation_date = datetime.now().strftime("%Y-%m-%d %H:%M")


def sanitize_content(text: str) -> str:
    """
    Rimuove residui di istruzioni del template dall'output dell'LLM.
    """
    # 1. Rimuove commenti HTML (<!-- ... -->) anche multi-riga
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)

    # 2. Rimuove placeholder angolari (<nome azienda>, <inserire qui>, ...)
    #    ma NON tag HTML legittimi come <br> o link markdown
    text = re.sub(r"<(?!br|http|a |/a|img)[A-Za-z][^>]*>", "", text)

    # 3. Rimuove placeholder tra parentesi quadre
    text = re.sub(r"\[(?:inserire|insert|TODO|enter|specify|add|fill)[^\]]*\]",
                  "", text, flags=re.IGNORECASE)

    # 4. Rimuove righe che sono pura istruzione (iniziano con keyword tipiche)
    instruction_markers = [
        "describe here", "list here", "enter here", "specify here",
        "fill in", "add here", "update this", "note:", "todo:",
    ]
    cleaned_lines = []
    for line in text.split("\n"):
        stripped = line.strip().lower()
        if any(stripped.startswith(marker) for marker in instruction_markers):
            continue
        cleaned_lines.append(line)
    text = "\n".join(cleaned_lines)

    # 5. Rimuove righe vuote multiple consecutive (pulizia finale)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def parse_field_value_table(markdown_text: str) -> dict[str, str]:
    """
    Estrae coppie {field: value} da una tabella Markdown | Field | Value |.
    Ignora righe di intestazione e separatori.
    """
    result = {}
    for line in markdown_text.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        parts = [cell.strip() for cell in line.strip("|").split("|")]
        if len(parts) < 2:
            continue
        field, value = parts[0], parts[1]
        if field.lower() in ("field", "") or set(field) <= set("-: "):
            continue
        result[field] = value
    return result


def recompose_transposed_table(compiled_sections: list) -> str:
    """
    Assembla una tabella Markdown trasposta rispetto al template OpenRegulatory:
    - righe = record
    - colonne = campi
    """
    records: list[tuple[str, dict]] = []
    for cs in compiled_sections:
        if cs.is_abstention:
            records.append((cs.section.title, {}))
        else:
            clean = sanitize_content(cs.generated_content)
            records.append((cs.section.title, parse_field_value_table(clean)))

    # Unione ordinata dei campi (preserva ordine di prima apparizione)
    seen_fields: list[str] = []
    for _, data in records:
        for field in data:
            if field not in seen_fields:
                seen_fields.append(field)

    if not seen_fields:
        return "*Nessun dato strutturato trovato nelle sezioni.*"

    col_headers = [f"**{field}**" for field in seen_fields]
    separator   = ["---"] * len(col_headers)

    rows = [col_headers, separator]
    for _, data in records:
        row = [data.get(field, "N/A") for field in seen_fields]
        rows.append(row)

    return "\n".join("| " + " | ".join(row) + " |" for row in rows)


def format_sources(sources: list[str]) -> list[str]:
    """Formatta la lista delle fonti in Markdown. Restituisce [] se vuota."""
    if not sources:
        return []
    return ["*Fonti:*", "", " | ".join(sources), ""]


def recompose_document(compiled: CompiledDocument, transposed: bool = False) -> str:
    """
    Assembla un documento Markdown finale dalle sezioni compilate.

    Args:
        compiled: il documento compilato con tutte le sezioni
        transposed: True  → Caso 1: tabella trasposta unica, False → Caso 2: sezioni separate
    """
    # --- HEADER ---
    lines = [
        f"# Compliance Report - {compiled.template.title}",
        "",
        f"**Repository:** {compiled.project_name}",
        f"**Template:** OpenRegulatory - {compiled.template.file_name}",
        f"**Generated by:** CRAG Compliance Analyzer",
        f"**Date:** {compiled.generation_date}",
        "",
        f"Questo report è stato generato automaticamente a partire dal template "
        f"regolatorio OpenRegulatory: {compiled.template.title}.",
        "",
    ]

    # --- RIEPILOGO COMPLETEZZA ---
    total     = len(compiled.sections)
    filled    = sum(1 for s in compiled.sections if not s.is_abstention)
    abstained = total - filled

    lines.append("---")
    lines.append("")
    lines.append(f"**Compilato:** {filled}/{total}")
    if abstained > 0:
        lines.append(f"**Sezioni con dati mancanti:** {abstained}")
        abstention_titles = [s.section.title for s in compiled.sections if s.is_abstention]
        lines.append("  - " + "\n  - ".join(abstention_titles))
    lines.append("")
    lines.append("---")
    lines.append("")

    # Titolo della sezione target (sfrutta il nuovo campo in ParsedTemplate)
    target_section = compiled.template.target_table_section
    section_title  = target_section.title if target_section else compiled.template.title

    # --- CASO 1: tabella trasposta unica ---
    if transposed and compiled.sections:
        lines.append(f"## {section_title}")
        lines.append("")
        lines.append(recompose_transposed_table(compiled.sections))
        lines.append("")

        # Fonti aggregate in fondo
        all_sources: list[str] = []
        for cs in compiled.sections:
            for src in (cs.sources or []):
                if src and src not in all_sources:
                    all_sources.append(src)
        lines.extend(format_sources(all_sources))

    # --- CASO 2: sezioni separate ---
    else:
        for cs in compiled.sections:
            lines.append(f"## {cs.section.title}")
            lines.append("")

            if cs.is_abstention:
                lines.append(f"> **[INFORMAZIONE NON DISPONIBILE]** {ABSTENTION_MSG}")
                lines.append("")
            else:
                lines.append(sanitize_content(cs.generated_content))
                lines.append("")

            lines.extend(format_sources(cs.sources or []))

    return "\n".join(lines)


def save_document(content: str, output_path: str) -> None:
    """Salva il documento Markdown."""
    Path(output_path).parent.mkdir(parents = True, exist_ok = True)
    Path(output_path).write_text(content, encoding = "utf-8")
    print(f"  Documento salvato: {os.path.relpath(output_path)}")


def get_output_path(template: ParsedTemplate, output_dir: str) -> str:
    """Genera il percorso di output per il documento compilato."""
    stem = Path(template.file_name).stem
    date_str = datetime.now().strftime("%Y%m%d")
    filename = f"{stem}_compiled_{date_str}.md"
    print(f"Output path: {str(Path(output_dir) / filename)}")
    return str(Path(output_dir) / filename)